#!/usr/bin/env bash
# =============================================================================
#  Generate /etc/nginx/conf.d/cloudflare-realip.conf
#
#      sudo bash deploy/nginx/cloudflare-realip.sh
#
#  Two things come out of this, both needed because Cloudflare sits in front of
#  the origin:
#
#   1. set_real_ip_from for every Cloudflare range, so $remote_addr is the
#      actual visitor. Without it the access log records a Cloudflare edge
#      address for every request and any IP-based rule is meaningless.
#
#   2. a $cf_forwarded_proto map. Cloudflare terminates TLS and speaks plain
#      HTTP to us, so nginx's own $scheme is "http" even when the visitor is on
#      HTTPS. Passing that through makes the app build http:// absolute URLs and
#      causes cookies marked Secure to be dropped — you get an endless
#      redirect-to-login loop that only reproduces through Cloudflare, never
#      when you curl the origin directly.
#
#  Cloudflare publishes these ranges and they change. Re-run after a change;
#  a monthly cron entry is in deploy/README.md.
# =============================================================================
set -euo pipefail

OUT="${OUT:-/etc/nginx/conf.d/cloudflare-realip.conf}"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

fetch() {
  curl -fsS --max-time 20 "$1" || return 1
}

echo "Fetching Cloudflare ranges..."
v4="$(fetch https://www.cloudflare.com/ips-v4 || true)"
v6="$(fetch https://www.cloudflare.com/ips-v6 || true)"

# Refuse to write a half-empty file. An empty set means no set_real_ip_from at
# all, which silently reverts every client IP to the Cloudflare edge — the
# failure this script exists to prevent.
if [[ -z "$v4" || -z "$v6" ]]; then
  echo "Could not fetch the ranges (no network?). Leaving the existing file alone." >&2
  [[ -f "$OUT" ]] && { echo "Existing $OUT kept."; exit 0; }
  echo "No existing file either — nginx will fail to start until this succeeds." >&2
  exit 1
fi

{
  echo "# Generated by deploy/nginx/cloudflare-realip.sh on $(date -Is)"
  echo "# Do not edit by hand — re-run the script."
  echo
  while read -r cidr; do [[ -n "$cidr" ]] && echo "set_real_ip_from ${cidr};"; done <<< "$v4"
  while read -r cidr; do [[ -n "$cidr" ]] && echo "set_real_ip_from ${cidr};"; done <<< "$v6"
  echo
  echo "real_ip_header CF-Connecting-IP;"
  echo "real_ip_recursive on;"
  echo
  echo "# Cloudflare speaks HTTP to the origin even when the visitor is on HTTPS."
  echo "# Trust its header when present; fall back to our own scheme when the"
  echo "# request did not come through Cloudflare (a direct hit on the origin IP)."
  echo "map \$http_x_forwarded_proto \$cf_forwarded_proto {"
  echo "    default \$scheme;"
  echo "    https   https;"
  echo "    http    http;"
  echo "}"
  echo
  echo "# Connection header for the upstream. Sending \"upgrade\" unconditionally"
  echo "# is the common copy-paste error: it breaks keepalive on ordinary"
  echo "# requests, because every response then carries a Connection: upgrade the"
  echo "# client never asked for. Echo it only when the client actually asked."
  echo "map \$http_upgrade \$connection_upgrade {"
  echo "    default upgrade;"
  echo "    ''      close;"
  echo "}"
} > "$TMP"

count="$(grep -c '^set_real_ip_from' "$TMP")"
[[ "$count" -ge 10 ]] || { echo "Only $count ranges parsed — that looks wrong, not writing." >&2; exit 1; }

install -m 0644 "$TMP" "$OUT"
echo "Wrote $OUT ($count Cloudflare ranges)"

if nginx -t 2>/dev/null; then
  echo "nginx config is valid. Reload with: sudo systemctl reload nginx"
else
  echo "WARNING: nginx -t failed — check the output of 'sudo nginx -t'." >&2
fi
